apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "12h"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.org/server-snippet: "proxy_ssl_verify off;"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^(/mytest)$ $1/ permanent;
spec:
  rules:
  - http:
      paths:
      - path: /mytest(/|$)(.*)
        backend:
          serviceName: hello-v1
          servicePort: 8080
