apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
          #  - host: itrm.example
  - http:
      paths:
      - path: /mytest(/|$)(.*)
        backend:
          serviceName: deployment
          servicePort: 3000
